//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
        }

        [Display(Name = "Mã đơn đặt hàng")]
        public string MaDonDatHang { get; set; }

        [Display(Name = "Mã khách hàng")]
        public string MaKhachHang { get; set; }

        [Display(Name = "Mã nhân viên")]
        [Required(ErrorMessage = "Chưa nhập mã nhân viên")]
        public string MaNhanVien { get; set; }

        [Display(Name = "Đơn vị vận chuyển")]
        public string MaDonViVanChuyen { get; set; }

        [Display(Name = "Ngày đặt hàng")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayDatHang { get; set; }

        [Display(Name = "Ngày giao hàng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }

        [Display(Name = "Địa chỉ giao")]
        public string DiaChiGiao { get; set; }

        [Display(Name = "Tình trạng")]
        public Nullable<int> TinhTrang { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual DonViVanChuyen DonViVanChuyen { get; set; }
    }
}
