//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DonViVanChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViVanChuyen()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
        }

        [Display(Name = "Mã đơn vị")]
        public string MaDonVi { get; set; }

        [Display(Name = "Tên đơn vị")]
        [Required(ErrorMessage = "Chưa nhập tên đơn vị")]
        public string TenDonVi { get; set; }

        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        public string SDT { get; set; }

        [Required(ErrorMessage = "Chưa nhập Email")]
        public string Email { get; set; }

        [Display(Name = "Ảnh đơn vị vận chuyển")]
        public string AnhDVVC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
    }
}
