//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBGD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
            this.PhanHois = new HashSet<PhanHoi>();
        }

        [Display(Name = "Mã sản phẩm")]
        [Required(ErrorMessage = "Chưa nhập mã sản phẩm")]
        public string MaSanPham { get; set; }

        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Chưa nhập tên sản phẩm")]
        public string TenSanPham { get; set; }

        [Display(Name = "Nhãn hiệu")]
        public string MaNhanHieu { get; set; }

        [Display(Name = "Loại sản phẩm")]
        public string MaLoaiSanPham { get; set; }

        [Display(Name = "Màu sắc")]
        [Required(ErrorMessage = "*")]
        public string MauSac { get; set; }

        [Display(Name = "Kích thước")]
        [Required(ErrorMessage = "*")]
        public string KichThuoc { get; set; }
        [Display(Name = "Đơn giá")]
        [Required(ErrorMessage = "Chưa nhập đơn giá")]
        public int DonGia { get; set; }

        [Display(Name = "Tình trạng")]
        [Required(ErrorMessage = "Chưa cập nhật tình trạng")]
        public string TinhTrang { get; set; }

        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Chưa thêm mô tả")]
        public string MoTa { get; set; }
        [Display(Name = "Ảnh sản phẩm")]
        public string AnhSP { get; set; }
        [Display(Name = "Giới tính")]
        public Nullable<bool> GioiTinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhanHieu NhanHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
